coverage:
  status:
    project:
      default:
        target: 95
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "pyppium"
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false